/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/results` | `/results`; params?: Router.UnknownInputParams; } | { pathname: `/components/calculateButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/colorByNumber`; params?: Router.UnknownInputParams; } | { pathname: `/components/numberInputs`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/buttons.test`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/functions.test`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/results` | `/results`; params?: Router.UnknownOutputParams; } | { pathname: `/components/calculateButton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/colorByNumber`; params?: Router.UnknownOutputParams; } | { pathname: `/components/numberInputs`; params?: Router.UnknownOutputParams; } | { pathname: `/__tests__/buttons.test`; params?: Router.UnknownOutputParams; } | { pathname: `/__tests__/functions.test`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/results${`?${string}` | `#${string}` | ''}` | `/results${`?${string}` | `#${string}` | ''}` | `/components/calculateButton${`?${string}` | `#${string}` | ''}` | `/components/colorByNumber${`?${string}` | `#${string}` | ''}` | `/components/numberInputs${`?${string}` | `#${string}` | ''}` | `/__tests__/buttons.test${`?${string}` | `#${string}` | ''}` | `/__tests__/functions.test${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/results` | `/results`; params?: Router.UnknownInputParams; } | { pathname: `/components/calculateButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/colorByNumber`; params?: Router.UnknownInputParams; } | { pathname: `/components/numberInputs`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/buttons.test`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/functions.test`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
