/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/start`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/example${'/(tabs)'}/explore` | `/example/explore`; params?: Router.UnknownInputParams; } | { pathname: `/example${'/(tabs)'}` | `/example`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/navigationSetup`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/types`; params?: Router.UnknownInputParams; } | { pathname: `/screens/entries`; params?: Router.UnknownInputParams; } | { pathname: `/example/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/start`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/example${'/(tabs)'}/explore` | `/example/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/example${'/(tabs)'}` | `/example`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/navigationSetup`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/types`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/entries`; params?: Router.UnknownOutputParams; } | { pathname: `/example/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/start${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/example${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/example/explore${`?${string}` | `#${string}` | ''}` | `/example${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/example${`?${string}` | `#${string}` | ''}` | `/navigation/navigationSetup${`?${string}` | `#${string}` | ''}` | `/navigation/types${`?${string}` | `#${string}` | ''}` | `/screens/entries${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/start`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/example${'/(tabs)'}/explore` | `/example/explore`; params?: Router.UnknownInputParams; } | { pathname: `/example${'/(tabs)'}` | `/example`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/navigationSetup`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/types`; params?: Router.UnknownInputParams; } | { pathname: `/screens/entries`; params?: Router.UnknownInputParams; } | `/example/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/example/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
