/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/example/+not-found`; params?: Router.UnknownInputParams; } | { pathname: `/example${'/(tabs)'}/explore` | `/example/explore`; params?: Router.UnknownInputParams; } | { pathname: `/example${'/(tabs)'}/index` | `/example/index`; params?: Router.UnknownInputParams; } | { pathname: `/screens/entries`; params?: Router.UnknownInputParams; } | { pathname: `/start`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/types`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/navigationSetup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/example/+not-found`; params?: Router.UnknownOutputParams; } | { pathname: `/example${'/(tabs)'}/explore` | `/example/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/example${'/(tabs)'}/index` | `/example/index`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/entries`; params?: Router.UnknownOutputParams; } | { pathname: `/start`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/types`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/navigationSetup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/example/+not-found${`?${string}` | `#${string}` | ''}` | `/example${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/example/explore${`?${string}` | `#${string}` | ''}` | `/example${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/example/index${`?${string}` | `#${string}` | ''}` | `/screens/entries${`?${string}` | `#${string}` | ''}` | `/start${`?${string}` | `#${string}` | ''}` | `/navigation/types${`?${string}` | `#${string}` | ''}` | `/navigation/navigationSetup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/example/+not-found`; params?: Router.UnknownInputParams; } | { pathname: `/example${'/(tabs)'}/explore` | `/example/explore`; params?: Router.UnknownInputParams; } | { pathname: `/example${'/(tabs)'}/index` | `/example/index`; params?: Router.UnknownInputParams; } | { pathname: `/screens/entries`; params?: Router.UnknownInputParams; } | { pathname: `/start`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/types`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/navigationSetup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
