services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./backend:/app
    environment:
      - PORT=8000
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    working_dir: /app
    command: npx expo start --tunnel --clear
    ports:
      - "19000:19000"  # Expo Dev Server
      - "19001:19001"  # Expo Dev Tools
      - "19002:19002"  # Debugger
      - "8081:8081"    # Metro Bundler
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
      - metro-cache:/app/node_modules/.cache
      - expo-cache:/app/.expo
    stdin_open: true
    tty: true

volumes:
  node_modules:
  metro-cache:
  expo-cache:
